spring.application.name=software-engineers
# Making this part of env.properties
# spring.datasource.url=jdb:postgresql://localhost:5332/amigos

# Import secrets
spring.config.import=env.properties

# Secrets
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
# db persists after app is restarted
spring.jpa.hibernate.ddl_auto=update
# db deleted after app is restarted
#spring.jpa.hibernate.ddl_auto=create-drop

# DIALECT NO LONGER NEEDED
# SQL dialect makes Hibernate generate better SQL for the chosen DB
# For mySQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# For PostgreSQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Not using these in this project

# Open API change URL
# springdoc.api-docs.path=/api-docs

# Spring Actuator
# management.endpoints.web.exposure.include=*
# management.endpoint.health.show-details=always

# Logging - SLF4J
# package level
#logging.level.com.bernardnash.vendor=DEBUG
# application level - including all Spring very verbose - not a good idea
#logging.level.root=DEBUG